### ISSUE TITLE
Handle NPE while reading OffsetsForTimes on ConsumerOffsetClient

### ISSUE THREAD

**Issue by NamrathaSunkara** [cerner/common-kafka#39]
When trying to provide a small enough window to extract kafka OffsetsForTimes if there are no offsets being written during that time, the ConsumerOffsetClient.getOffsetsForTimes$1(ConsumerOffsetClient.java:148) returns a null which results in a Null Pointer Exception when trying read these offsets. We should be handling these NPEs instead.
`java.lang.NullPointerException
    at com.cerner.common.kafka.consumer.ConsumerOffsetClient.lambda$getOffsetsForTimes$1(ConsumerOffsetClient.java:148)
    at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1321)
    at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
    at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1699)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
    at com.cerner.common.kafka.consumer.ConsumerOffsetClient.getOffsetsForTimes(ConsumerOffsetClient.java:148)
    at com.cerner.pophealth.refrecord.extract.crunch.person.impl.helper.PersonUpdatedRecordIdsKafkaSourceReader.buildOffsetsFromTimestamp(PersonUpdatedRecordIdsKafkaSourceReader.java:115)
    at com.cerner.pophealth.refrecord.extract.crunch.person.impl.helper.PersonUpdatedRecordIdsKafkaSourceReader.read(PersonUpdatedRecordIdsKafkaSourceReader.java:97)
    at com.cerner.pophealth.refrecord.extract.crunch.person.impl.helper.PersonUpdatedRecordIdsKafkaSourceReader.readMessages(PersonUpdatedRecordIdsKafkaSourceReader.java:70)
    at com.cerner.pophealth.refrecord.extract.crunch.person.impl.PersonUpdatedExtractorImpl.doClusterExtract(PersonUpdatedExtractorImpl.java:118)
    at com.cerner.pophealth.refrecord.extract.crunch.person.impl.PersonUpdatedExtractorImpl.doClusterExtract(PersonUpdatedExtractorImpl.java:43)
    at com.cerner.pophealth.refrecord.extract.crunch.BaseExtractor.extract(BaseExtractor.java:157)
    at com.cerner.pophealth.refrecord.extract.crunch.person.impl.PersonUpdatedExtractorImpl.extractUpdatedIds(PersonUpdatedExtractorImpl.java:145)
    at com.cerner.pophealth.refrecord.console.extract.IncrementalExtractCommand.run(IncrementalExtractCommand.java:101)
    at com.cerner.kepler.commands.Command.run(Command.java:130)
    at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
    at com.cerner.kepler.commands.BasicCommandRunner.run(BasicCommandRunner.java:74)
    at com.cerner.kepler.commands.CommandRunner.run(CommandRunner.java:29)
    at com.cerner.kepler.commands.CommandRunner.run(CommandRunner.java:19)
    at com.cerner.pophealth.refrecord.console.extract.ExtractConsoleMain.main(ExtractConsoleMain.java:72)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
    at org.apache.hadoop.util.RunJar.main(RunJar.java:136)`

**Comment by bbaugher** [comment]
We will definitely fix this but I just saw that you can use [Kafka's AdminClient#https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java#L894](https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java#L894). Its available in Kafka 2.4+ and is probably lighter-weight than our offset client which uses an actual consumer
